# Generated by Django 4.1.2 on 2022-12-01 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='idSegmento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.segmento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idTipoVehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.tipovehiculo'),
            preserve_default=False,
        ),
    ]
