# Generated by Django 4.1.2 on 2022-12-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_vehiculo_idsegmento_vehiculo_idtipovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
