# Generated by Django 4.1.2 on 2022-12-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_vehiculo_publicar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenVO', models.ImageField(blank=True, null=True, upload_to='VOImagenes')),
                ('vo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.vehiculo')),
            ],
        ),
    ]
