# Generated by Django 4.1.2 on 2022-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_imgenvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagenVO',
            field=models.ImageField(blank=True, null=True, upload_to='VOImagenes'),
        ),
        migrations.DeleteModel(
            name='ImgenVehiculo',
        ),
    ]
