# Generated by Django 3.2.16 on 2022-12-06 01:10

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_mensaje_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fechaReserva',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
